// Front/TS/src/infrastructure/ui/Angular/src/app/friends/add/add-friend.component.ts
import { Component, Input, input, OnInit } from "@angular/core";
import { MemberDto } from "../../../../../../../domain/members/IMemberRepository";
import { NgIf } from "@angular/common";
import { FriendsViewModel } from "../FriendsViewModel";

@Component({
  selector: "add-friend",
  templateUrl: "./add-friend.component.html",
  styleUrls: ["./add-friend.component.scss"]
})

export class AddFriendComponent {
  
  @Input() member: MemberDto|undefined = undefined
  constructor(protected friendsViewModel: FriendsViewModel) { 
  }

  async AddFriend(memberId: string|undefined) {
    if(memberId != undefined){
      await this.friendsViewModel.AddFriend(memberId);
      this.member!.IsFriend = true;
    }
  }
}

// Front/TS/src/infrastructure/ui/Vue/src/components/AddFriendComponent.vue
<template>
    <button v-if="!member?.IsFriend" @click="AddFriend(member.Id)">Add</button>
</template>

<script lang="ts">
    import { inject, getCurrentInstance, type PropType } from 'vue'
    import { type MemberDto } from '../../../../../domain/members/IMemberRepository' 
import type { FriendsViewModel } from '../viewmodels/FriendsViewModel';
    
    export default {
        props: {
            member: Object as PropType<MemberDto>
        },
        setup(props) {
            const vm = inject<FriendsViewModel>('friendsviewmodel');
            const instance = getCurrentInstance();
            const member = props.member
            return {
                vm,
                instance,
                member
            }
        },
        methods: {
            async AddFriend(id: string) : Promise<void> {
                await this.vm?.AddFriend(id);
                this.member!.IsFriend = true;
                this.instance?.proxy?.$forceUpdate()
            }
        }
    }
</script>
