// Front/TS/src/infrastructure/ui/Vue/src/components/friends/AddFriendComponent.vue
<template>
    <button v-if="!member?.IsFriend" @click="AddFriend(member.Id)">Add</button>
</template>

<script lang="ts">
    import { inject, ref, getCurrentInstance, type PropType } from 'vue'
    import { FriendsController } from '../../../../../adapters/controllers/FriendsController'
    import { AddFriendPresenter } from '../../presenters/AddFriendPresenter'
    import { type MemberDto } from '../../../../../../domain/members/IMemberRepository' 
    
    export default {
        props: {
            member: Object as PropType<MemberDto>
        },
        setup(props) {
            const controller = inject<FriendsController>('friendsController');
            const addFriendPresenter = inject<AddFriendPresenter>('addFriendPresenter')
            addFriendPresenter?.Subscribe(controller!)
            const instance = getCurrentInstance();
            const member = props.member
            return {
                controller,
                instance,
                member
            }
        },
        methods: {
            async AddFriend(id: string) : Promise<void> {
                await this.controller?.AddFriend(id);
                this.member!.IsFriend = true;
                this.instance?.proxy?.$forceUpdate()
            }
        }
    }
</script>

// Front/TS/src/infrastructure/ui/Angular/src/app/friends/add/add-friend.component.ts
import { Component, Input, input, OnInit } from "@angular/core";
import { MemberDto } from "../../../../../../../domain/members/IMemberRepository";
import { NgIf } from "@angular/common";
import { FriendsController } from '../../../../../../adapters/controllers/FriendsController';
import { AddFriendPresenter } from '../../../presenters/AddFriendPresenter';

@Component({
  selector: "add-friend",
  templateUrl: "./add-friend.component.html",
  styleUrls: ["./add-friend.component.scss"],
  standalone: true,
  imports: [NgIf]
})

export class AddFriendComponent {
  
  @Input() member: MemberDto|undefined = undefined
  constructor(private friendsController: FriendsController,
              private addFriendPresenter: AddFriendPresenter) { 
    this.addFriendPresenter.Subscribe(this.friendsController)
  }

  async AddFriend(memberId: string|undefined) {
    if(memberId != undefined){
      await this.friendsController.AddFriend(memberId);
    }
  }
}
