// Front/TS/src/infrastructure/ui/Vue/src/components/friends/FriendsComponent.vue
<template>
    <div>
        <search-component @searched="update"></search-component>
        
        <ul v-if="viewModel.ShowFriends">
                <li v-for="friend in viewModel.Friends" :key="friend.Id">
                    {{ friend.Name }} 
                </li>
            </ul>
        <ul v-if="viewModel.ShowFriends === false">
                <li v-for="member in viewModel.Members" :key="member.Id">
                    {{ member.Name }} <add-friend-component :member="member"></add-friend-component>
                </li>
            </ul>
    </div>
</template>

<script lang="ts">
import { getCurrentInstance, inject, ref } from 'vue'
import SearchComponent from './SearchComponent.vue'
import AddFriendComponent from './AddFriendComponent.vue'
import { FriendsController } from '../../../../../adapters/controllers/FriendsController'
import type { RetrieveFriendsPresenter } from '../../presenters/RetrieveFriendsPresenter'
export default {
  components: { SearchComponent, AddFriendComponent },
    setup() {
        const controller = inject<FriendsController>('friendsController')
        const retrieveFriendsPresenter = inject<RetrieveFriendsPresenter>('retrieveFriendsPresenter')
        retrieveFriendsPresenter?.Subscribe(controller!)
        const viewModel: any = ref(controller!.vm);
        const current = getCurrentInstance()
        return {
            viewModel,
            controller,
            current
        }
    },
    async mounted(): Promise<void> {
        await this.controller!.GetFriends()
        this.current?.proxy?.$forceUpdate();
    },
    methods: {
        update() {
            this.current?.proxy?.$forceUpdate();
        }
    }
}

</script>

// Front/TS/src/infrastructure/ui/Angular/src/app/friends/friends.component.ts
import { Component, OnInit } from "@angular/core";
import { NgFor, NgIf } from "@angular/common";
import { SearchComponent } from "./search/search.component";
import { AddFriendComponent } from './add/add-friend.component';
import { RetrieveFriendsPresenter } from "../../presenters/RetrieveFriendsPresenter";
import { FriendsController } from "../../../../../adapters/controllers/FriendsController";

@Component({
  selector: "app-friends",
  templateUrl: "./friends.component.html",
  styleUrls: ["./friends.component.scss"],
  imports: [NgFor, NgIf, SearchComponent, AddFriendComponent],
  standalone: true
})

export class FriendsComponent implements OnInit {

  constructor(private friendsController: FriendsController,
              private retrieveFriendsPresenter: RetrieveFriendsPresenter){
    this.retrieveFriendsPresenter.Subscribe(this.friendsController)
  }

  protected viewModel: any = this.friendsController.vm;

  async ngOnInit(): Promise<void> {
    await this.friendsController.GetFriends();
  }
}
<search-friends />
<div class="center" *ngIf="viewModel.ShowFriends">
    <ul *ngFor="let friend of viewModel.Friends">
        <li>{{friend.Name}} </li>
    </ul>
</div>

<div class="center" *ngIf="!viewModel.ShowFriends">
    <ul *ngFor="let member of viewModel.Members">
        <li>{{member.Name}} <add-friend [member]="member" /></li>
    </ul>
</div>
